version: 2.1


orbs:
  maven: circleci/maven@1.2.0


jobs:
  build:
    docker:
      - image: openjdk
    steps:
      - checkout
      - run:
          name: show java version
          command: java --version
      - run:
          name: installation de maven
          command: apt-get update && apt-get install maven
workflows:
  say-hello-workflow:
    jobs:
      - build
