version: 2.1


orbs:
  maven: circleci/maven@1.2.0


jobs:
  build:
    docker:
      - image: openjdk
    steps:
      - checkout
      - run:
          name: show java version
          command: java --version
      - persist_to_workspace:
          root: ./src/main
          paths:
            - resources
      - run:
          name: multiple commands
          command: |
            echo "test"
            echo " env variable << CIRCLE_BUILD_NUM  <<"
  run:
    docker:
      - image: openjdk
    steps:
      - attach_workspace:
          at: /test
      - run:
          name: listing directory
          command: ls /test/resources
workflows:
  say-hello-workflow:
    jobs:
      - build
      - run:
          requires:
            - build
